[project]
name = "tidyml"
version = "0.1.0"
description = "A lightweight, human-readable markup language parser"
authors = [{ name="Gokul Kartha", email="kartha.gokul@gmail.com" }]
dependencies = []

[tool.setuptools]
packages = ["tidyml"]
